- hosts: all
  become: yes
  gather_facts: no

  vars_files:
    - vars.yml
  
  tasks:
  
  - name: Clone a github repository
    git:
      repo: https://github.com/avishoro/bootcamp-app.git
      dest: /home/avishai/bootcamp-app
      force: yes
      clone: yes
      update: yes

  - name: install node 
    shell: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs
      
  - name: Install nodejs
    apt:
        name: nodejs
        state: present

  - name: Npm initialization
    shell: npm init -y
    args:
        chdir: "/home/avishai/bootcamp-app/"

  - name: Install node dependencies
    shell: npm install
    args:
        chdir: "/home/avishai/bootcamp-app/"
        
  - name: install pm2
    npm:
      name: pm2
      global: yes

  - name: install pm2 startup
    shell: pm2 startup

  - name: Install packages based on package.json using the npm
    npm:
      path: /home/avishai/bootcamp-app
      state: present

  - name: add .env file
    copy:
        dest: "/home/avishai/bootcamp-app/.env"
        content: |
            # Host configuration
            PORT=8080
            HOST={{host}}
            # Postgres configuration
            PGHOST={{pghost}}
            PGUSERNAME={{pg_username}}
            PGDATABASE=postgres
            PGPASSWORD={{pg_password}}
            PGPORT=5432
            HOST_URL=http://{{LB_ip}}:8080
            COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
            NODE_ENV=development
            # Okta configuration
            OKTA_ORG_URL={{okta_url}}
            OKTA_CLIENT_ID={{okta_client_id}}
            OKTA_CLIENT_SECRET={{okta_client_secret}}
    
    tags:
         - env

  - name: run initdb script
    run_once: true
    shell: cd /home/avishai/bootcamp-app && npm run initdb
    register: initdb
    tags:
      - initdb

  - debug: msg="{{ initdb.stdout }}"
    run_once: true
    tags:
      - initdb

  - name: run app as pm2 process
    shell: cd /home/avishai/bootcamp-app &&  pm2 start npm -- run dev
    register: out
    tags:
      - run

  - debug: var=out.stdout_lines
  
  - name: save process to run at start app
    shell: pm2 save
